id: I52E92B81
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T16:32:39+00:00'
last_modified: '2022-06-07T15:24:32.141759+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11794
  title: འཇིགས་བྱེད་ཐེམ་སྐས་བཅོ་བརྒྱད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
  base:
    0EF4:
      image_group_id: I1KG11796
      title: ''
      total_pages: 426
      order: 1
      base_file: 0EF4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
