id: P001858
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG11794
  title: འཇིགས་བྱེད་ཐེམ་སྐས་བཅོ་བརྒྱད།
  author: ''
  volumes:
    63a4c34672404649b2a436dfa76da279:
      image_group_id: I1KG11796
      title: ''
      volume_number: 1
      total_pages: 426
      base_file: v001.txt
